import { Inter, Roboto_Mono } from 'next/font/google';
import './globals.css';

// If you specifically want Geist fonts, you need to use the local files
const geistSans = {
  variable: '--font-geist-sans',
  style: 'normal',
  className: 'font-sans'
};

const geistMono = {
  variable: '--font-geist-mono',
  style: 'normal',
  className: 'font-mono'
};

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
